---
title: "Lab 4: Interactive Dashboards"
author: Allen
format: 
  dashboard:
    orientation: columns
    logo: images/albatross.png
    theme: minty
    nav-buttons: 
      - icon: github
        href: https://github.com/TheAllenChoi
      - icon: linkedin
        href: https://www.linkedin.com/in/allen-choi/
server: shiny
---

```{r}
#| label: packages-initialize
#| context: setup
library(tidyverse)
library(here)
library(plotly)
library(ggridges)
library(leaflet)
library(rnaturalearth)
library(kableExtra)
library(shiny)
library(bslib)
```

```{r}
#| label: data-read-in
#| context: setup



# data <- readxl::read_xlsx(here("wgm2018-dataset-crosstabs-all-countries.xlsx"),
#                                sheet = 2)

# have to preprocess data before or shinyapp crashes maybe
# subset <- data |>
#   select(WP5, Q25, Regions_Report, Q11E)
# write.csv(subset, "data_subset.csv", row.names = FALSE)

data <- read_csv(here("data_subset.csv"), show_col_types = FALSE)
# data_dict <- readxl::read_xlsx(here("wgm2018-dataset-crosstabs-all-countries.xlsx"),
#                                sheet = 3)
# write.csv(data_dict, "data_dict.csv", row.names = FALSE)
data_dict <- read_csv(here("data_dict.csv"), show_col_types = FALSE)
```

# Trust in Vaccines (2018)

## {.sidebar}
```{r}
sliderInput("quantile", "Quantile", value = 0.5,
            min = 0.01, max = 0.99, step = 0.01)
```


## Over World Regions
```{r}
#| context: setup
data_dict_vaccine <- data_dict
data_dict_vaccine <- data_dict_vaccine[1, 3] |> 
  rename(country = `Variable Type & Codes*`) |> 
  separate_wider_delim(country, delim = ",", names_sep = "-")

data_dict_vaccine <- data_dict_vaccine[1, 1:ncol(data_dict_vaccine)-1]

country_code <- data.frame(t(data_dict_vaccine)) |> 
  separate_wider_delim(cols = `t.data_dict_vaccine.`,
                       delim = "=",
                       names_sep = "-") |> 
  rename(code = `t.data_dict_vaccine.-1`,
         country = `t.data_dict_vaccine.-2`) |> 
  mutate(code = as.numeric(code))

data_vaccine <- data |> 
  select(c(WP5, Q25, Regions_Report))
final <- data_vaccine |> 
  drop_na() |> 
  left_join(country_code, by = join_by(WP5 == code)) |> 
  select(-WP5) |> 
  mutate(Q25 = case_when(
    Q25 == 1 ~ 1,
    Q25 == 2 ~ 1,
    .default = 0
  )) |> 
  group_by(country) |>
  summarize(percentage = sum(Q25) / n()) 

regions <- data_vaccine |> 
  select(WP5, Regions_Report) |> 
  distinct(WP5, Regions_Report) |> 
  left_join(country_code, by = join_by(WP5 == code)) |> 
  mutate(region = case_when(
    Regions_Report %in% c(1, 2, 4, 5) ~ "Sub-Saharan Africa",
    Regions_Report %in% c(3, 13) ~ "Middle East / North Africa",
    Regions_Report %in% c(6, 7, 8) ~ "Americas",
    Regions_Report %in% c(9, 10, 11, 12) ~ "Asia",
    Regions_Report %in% c(15, 16, 17) ~ "Europe",
    Regions_Report %in% c(14) ~ "Former Soviet Union",
    .default = "Other"
  )) |> 
  select(country, region)
```

```{r}
#| title: Percentage of People who Believe Vaccines are Safe
#| context: server

output$plot <- renderPlot({
  final |> 
    left_join(regions, by = join_by(country == country)) |> 
    filter(region != "Other") |> 
    mutate(region = factor(region,
                           levels = c("Former Soviet Union", "Europe", "Americas",
                                      "Middle East / North Africa", "Sub-Saharan Africa", "Asia"))) |> 
    ggplot(aes(y = region, x = percentage,
               fill = region,
               group = region)) +
    stat_density_ridges(quantiles = input$quantile, quantile_lines = TRUE, alpha = 0.9) +
    theme_minimal() +
    theme(legend.position = "none",
          panel.grid.minor.y = element_blank(),
          panel.grid.major.y = element_blank(),
          title = element_text(face = "bold")) +
    labs(y = "",
         x = "") +
    scale_x_continuous(limits = c(.2, 1), labels = scales::label_percent()) +
    scale_fill_brewer(palette = "Spectral")
})
```

```{r}
plotOutput("plot")
```


## Overview of the data
```{r}
#| context: setup
final |> 
  left_join(regions, by = join_by(country == country)) |> 
  arrange(desc(percentage)) |> 
  kable() |> 
  kable_styling()
```



# Map of Percent Trust in Doctors/Nurses

::: panel-tabset
## 2018 {width="70%"}

```{r}
#| title: Response to Trust in Doctors/Nurses
#| context: setup

data_doctor <- data |> 
  select(WP5, Q11E)

data_dict <- data_dict[1, 3] |> 
  rename(country = `Variable Type & Codes*`) |> 
  separate_wider_delim(country, delim = ",", names_sep = "-")

data_dict <- data_dict[1, 1:ncol(data_dict)-1]

country_code <- data.frame(t(data_dict)) |> 
  separate_wider_delim(cols = `t.data_dict.`,
                       delim = "=",
                       names_sep = "-") |> 
  rename(code = `t.data_dict.-1`,
         country = `t.data_dict.-2`) |> 
  mutate(code = as.numeric(code))

map_data <- data_doctor |> 
  mutate(Q11E = as.character(Q11E)) |> 
  group_by(WP5) |> 
  mutate(Q11E = case_when(
    Q11E == 1 ~ 1,
    Q11E == 2 ~ 1,
    .default = 0
  )) |> 
  summarize(percent = (sum(Q11E) / n())) |> 
  left_join(country_code, by = join_by(WP5 == code)) |> 
  mutate(country = case_when(
    country == "United States" ~ "United States of America",
    .default = country
  ))
mean1 <- mean(map_data$percent)
median1 <- median(map_data$percent)
percentile_25_1 <- as.numeric(quantile(map_data$percent, 0.25))
percentile_75_1 <- as.numeric(quantile(map_data$percent, 0.75))

country_map_info <- ne_countries(returnclass = "sf")
country_map_info <- country_map_info |> 
  inner_join(map_data, by = join_by(name == country)) |> 
  mutate(percent = percent * 100,
         percent = round(percent, digits = 2))
  
colors <- colorNumeric(palette = "YlGnBu", domain = country_map_info$percent)
country_map_info |> 
  leaflet() |> 
  addTiles(options = tileOptions(noWrap = TRUE)) |> 
  addPolygons(color = colors(country_map_info$percent),
              weight = 2,
              popup = paste0(
                "Country:", " ", country_map_info$name, " <br> ",
                "Percent:", " ", country_map_info$percent),
              label = paste0(
                "Percent:", " ", country_map_info$percent, "%"),
              fillOpacity = 1) |> 
  addLegend(pal = colors, values = country_map_info$percent,
            title = "Percent <br> (Response = 'A lot'/'Some')",
            opacity = 1)
```

## 2020

```{r}
#| title: Response to Trust in Doctors/Nurses
#| context: setup
doctor_2020 <- read_csv("wgm_full_wave2_public_file_final (1)_csv.csv",
                        col_select = c("COUNTRYNEW", "W5E"), show_col_types = FALSE)

map_data <- doctor_2020 |> 
  group_by(COUNTRYNEW) |> 
  mutate(W5E = case_when(
    W5E == 1 ~ 1,
    W5E == 2 ~ 1,
    .default = 0
  )) |> 
  summarize(percent = (sum(W5E) / n())) |> 
  mutate(COUNTRYNEW = case_when(
    COUNTRYNEW == "United States" ~ "United States of America",
    .default = COUNTRYNEW
  ))

# mean(map_data$percent)
country_map_info <- ne_countries(returnclass = "sf")
country_map_info <- country_map_info |> 
  inner_join(map_data, by = join_by(name == COUNTRYNEW)) |> 
  mutate(percent = percent * 100,
         percent = round(percent, digits = 2))
  
colors <- colorNumeric(palette = "YlGnBu", domain = country_map_info$percent)
country_map_info |> 
  leaflet() |> 
  addTiles(options = tileOptions(noWrap = TRUE)) |> 
  addPolygons(color = colors(country_map_info$percent),
              weight = 2,
              popup = paste0(
                "Country:", " ", country_map_info$name, " <br> ",
                "Percent:", " ", country_map_info$percent),
              label = paste0(
                "Percent:", " ", country_map_info$percent, "%"),
              fillOpacity = 1) |> 
  addLegend(pal = colors, values = country_map_info$percent,
            title = "Percent <br> (Response = 'A lot'/'Some')",
            opacity = 1)

mean2 <- mean(map_data$percent)
median2 <- median(map_data$percent)
percentile_25_2 <- as.numeric(quantile(map_data$percent, 0.25))
percentile_75_2 <- as.numeric(quantile(map_data$percent, 0.75))
```
:::

## {.sidebar}
```{r}
selectInput("statistics", "Statistic",
            c("Mean", "Median", "25th Percentile", "75th Percentile"))
```

## Row {width="30%"}

::: {.card title="2018 Trust"}
```{r}
textOutput("text1")
```

```{r}
#| context: server

stat1 <- reactive({
  if (input$statistics == "Mean") {
    round(mean1, digits = 4) * 100
  } else if (input$statistics == "Median") {
    round(median1, digits = 4) * 100
  } else if (input$statistics == "25th Percentile") {
    round(percentile_25_1, digits = 4) * 100
  } else if (input$statistics == "75th Percentile") {
    round(percentile_75_1, digits = 4) * 100
}
})

output$text1 <- renderText({
  paste("The", input$statistics, "of the percentage of people who would say
        they trust their doctors and nurses in 2018 is", paste0(stat1(), "%"))
})
```

:::

::: {.card title="2020 Trust"}
```{r}
textOutput("text2")
```

```{r}
#| context: server
stat2 <- reactive({
  if (input$statistics == "Mean") {
    round(mean2, digits = 4) * 100
  } else if (input$statistics == "Median") {
    round(median2, digits = 4) * 100
  } else if (input$statistics == "25th Percentile") {
    round(percentile_25_2, digits = 4) * 100
  } else if (input$statistics == "75th Percentile") {
    round(percentile_75_2, digits = 4) * 100
}
})

output$text2 <- renderText({
  paste("The", input$statistics, "of the percentage of people who would say
        they trust their doctors and nurses in 2020 is", paste0(stat2(), "%"))
})
```
:::

